version: '3.8'

services:
  app:
    build: .
    container_name: webmeclibr
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_NAME=db-webmeclibr
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-123456}
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - webmeclibr-net

  postgres:
    image: postgres:16-alpine
    container_name: webmeclibr-db
    restart: always
    environment:
      - POSTGRES_DB=webmeclibr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-123456}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webmeclibr-net

networks:
  webmeclibr-net:
    driver: bridge

volumes:
  pgdata:
